import { MigrationInterface, QueryRunner } from "typeorm";

export class InitMigration1762381625159 implements MigrationInterface {
    name = 'InitMigration1762381625159'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_membership" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rol" varchar CHECK( "rol" IN ('PROPIETARIO','MIEMBRO') ) NOT NULL DEFAULT ('MIEMBRO'), "fechaIngreso" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "teamId" integer NOT NULL, CONSTRAINT "UQ_8cbaee95bef7db57d99430b302b" UNIQUE ("userId", "teamId"), CONSTRAINT "FK_f587b1be7b7595b5af79a2fd008" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_membership"("id", "rol", "fechaIngreso", "userId", "teamId") SELECT "id", "rol", "fechaIngreso", "userId", "teamId" FROM "membership"`);
        await queryRunner.query(`DROP TABLE "membership"`);
        await queryRunner.query(`ALTER TABLE "temporary_membership" RENAME TO "membership"`);
        await queryRunner.query(`CREATE TABLE "temporary_task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "description" varchar NOT NULL, "userId" integer, "teamId" integer, "priority" text NOT NULL DEFAULT ('media'), "estado" varchar CHECK( "estado" IN ('PENDIENTE','EN_CURSO','FINALIZADA','CANCELADA') ) NOT NULL DEFAULT ('PENDIENTE'), "dueDate" datetime, "fechaCreacion" datetime NOT NULL DEFAULT (datetime('now')), "historialEstadosId" integer, CONSTRAINT "FK_81dff849ce37d44c8821afdb197" FOREIGN KEY ("historialEstadosId") REFERENCES "historial_estado" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f316d3fe53497d4d8a2957db8b9" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de59b0c5e20f83310101e5ca835" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_task"("id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId") SELECT "id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId" FROM "task"`);
        await queryRunner.query(`DROP TABLE "task"`);
        await queryRunner.query(`ALTER TABLE "temporary_task" RENAME TO "task"`);
        await queryRunner.query(`CREATE TABLE "temporary_user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "rol" varchar NOT NULL, "email" varchar NOT NULL, "password" varchar NOT NULL, CONSTRAINT "UQ_ed766a9782779b8390a2a81f444" UNIQUE ("email"))`);
        await queryRunner.query(`INSERT INTO "temporary_user"("id", "name", "rol") SELECT "id", "name", "rol" FROM "user"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`ALTER TABLE "temporary_user" RENAME TO "user"`);
        await queryRunner.query(`CREATE TABLE "temporary_membership" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rol" varchar CHECK( "rol" IN ('PROPIETARIO','MIEMBRO') ) NOT NULL DEFAULT ('MIEMBRO'), "fechaIngreso" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "teamId" integer NOT NULL, CONSTRAINT "UQ_8cbaee95bef7db57d99430b302b" UNIQUE ("userId", "teamId"), CONSTRAINT "FK_f587b1be7b7595b5af79a2fd008" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_membership"("id", "rol", "fechaIngreso", "userId", "teamId") SELECT "id", "rol", "fechaIngreso", "userId", "teamId" FROM "membership"`);
        await queryRunner.query(`DROP TABLE "membership"`);
        await queryRunner.query(`ALTER TABLE "temporary_membership" RENAME TO "membership"`);
        await queryRunner.query(`CREATE TABLE "temporary_task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "description" varchar NOT NULL, "userId" integer, "teamId" integer, "priority" text NOT NULL DEFAULT ('media'), "estado" varchar CHECK( "estado" IN ('PENDIENTE','EN_CURSO','FINALIZADA','CANCELADA') ) NOT NULL DEFAULT ('PENDIENTE'), "dueDate" datetime, "fechaCreacion" datetime NOT NULL DEFAULT (datetime('now')), "historialEstadosId" integer, CONSTRAINT "FK_81dff849ce37d44c8821afdb197" FOREIGN KEY ("historialEstadosId") REFERENCES "historial_estado" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f316d3fe53497d4d8a2957db8b9" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de59b0c5e20f83310101e5ca835" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_task"("id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId") SELECT "id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId" FROM "task"`);
        await queryRunner.query(`DROP TABLE "task"`);
        await queryRunner.query(`ALTER TABLE "temporary_task" RENAME TO "task"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "task" RENAME TO "temporary_task"`);
        await queryRunner.query(`CREATE TABLE "task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "description" varchar NOT NULL, "userId" integer, "teamId" integer, "priority" text NOT NULL DEFAULT ('media'), "estado" varchar CHECK( "estado" IN ('PENDIENTE','EN_CURSO','FINALIZADA','CANCELADA') ) NOT NULL DEFAULT ('PENDIENTE'), "dueDate" datetime, "fechaCreacion" datetime NOT NULL DEFAULT (datetime('now')), "historialEstadosId" integer, CONSTRAINT "FK_81dff849ce37d44c8821afdb197" FOREIGN KEY ("historialEstadosId") REFERENCES "historial_estado" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f316d3fe53497d4d8a2957db8b9" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de59b0c5e20f83310101e5ca835" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "task"("id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId") SELECT "id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId" FROM "temporary_task"`);
        await queryRunner.query(`DROP TABLE "temporary_task"`);
        await queryRunner.query(`ALTER TABLE "membership" RENAME TO "temporary_membership"`);
        await queryRunner.query(`CREATE TABLE "membership" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rol" varchar CHECK( "rol" IN ('PROPIETARIO','MIEMBRO') ) NOT NULL DEFAULT ('MIEMBRO'), "fechaIngreso" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "teamId" integer NOT NULL, CONSTRAINT "UQ_8cbaee95bef7db57d99430b302b" UNIQUE ("userId", "teamId"), CONSTRAINT "FK_f587b1be7b7595b5af79a2fd008" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "membership"("id", "rol", "fechaIngreso", "userId", "teamId") SELECT "id", "rol", "fechaIngreso", "userId", "teamId" FROM "temporary_membership"`);
        await queryRunner.query(`DROP TABLE "temporary_membership"`);
        await queryRunner.query(`ALTER TABLE "user" RENAME TO "temporary_user"`);
        await queryRunner.query(`CREATE TABLE "user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "rol" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "user"("id", "name", "rol") SELECT "id", "name", "rol" FROM "temporary_user"`);
        await queryRunner.query(`DROP TABLE "temporary_user"`);
        await queryRunner.query(`ALTER TABLE "task" RENAME TO "temporary_task"`);
        await queryRunner.query(`CREATE TABLE "task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "description" varchar NOT NULL, "userId" integer, "teamId" integer, "priority" text NOT NULL DEFAULT ('media'), "estado" varchar CHECK( "estado" IN ('PENDIENTE','EN_CURSO','FINALIZADA','CANCELADA') ) NOT NULL DEFAULT ('PENDIENTE'), "dueDate" datetime, "fechaCreacion" datetime NOT NULL DEFAULT (datetime('now')), "historialEstadosId" integer, CONSTRAINT "FK_81dff849ce37d44c8821afdb197" FOREIGN KEY ("historialEstadosId") REFERENCES "historial_estado" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f316d3fe53497d4d8a2957db8b9" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de59b0c5e20f83310101e5ca835" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "task"("id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId") SELECT "id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId" FROM "temporary_task"`);
        await queryRunner.query(`DROP TABLE "temporary_task"`);
        await queryRunner.query(`ALTER TABLE "membership" RENAME TO "temporary_membership"`);
        await queryRunner.query(`CREATE TABLE "membership" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rol" varchar CHECK( "rol" IN ('PROPIETARIO','MIEMBRO') ) NOT NULL DEFAULT ('MIEMBRO'), "fechaIngreso" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "teamId" integer NOT NULL, CONSTRAINT "UQ_8cbaee95bef7db57d99430b302b" UNIQUE ("userId", "teamId"), CONSTRAINT "FK_f587b1be7b7595b5af79a2fd008" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "membership"("id", "rol", "fechaIngreso", "userId", "teamId") SELECT "id", "rol", "fechaIngreso", "userId", "teamId" FROM "temporary_membership"`);
        await queryRunner.query(`DROP TABLE "temporary_membership"`);
    }

}
