import { MigrationInterface, QueryRunner } from "typeorm";

export class InitMigration1765232921479 implements MigrationInterface {
    name = 'InitMigration1765232921479'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_membership" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rol" varchar CHECK( "rol" IN ('PROPIETARIO','MIEMBRO') ) NOT NULL DEFAULT ('MIEMBRO'), "fechaIngreso" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "teamId" integer NOT NULL, CONSTRAINT "UQ_8cbaee95bef7db57d99430b302b" UNIQUE ("userId", "teamId"), CONSTRAINT "FK_f587b1be7b7595b5af79a2fd008" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_membership"("id", "rol", "fechaIngreso", "userId", "teamId") SELECT "id", "rol", "fechaIngreso", "userId", "teamId" FROM "membership"`);
        await queryRunner.query(`DROP TABLE "membership"`);
        await queryRunner.query(`ALTER TABLE "temporary_membership" RENAME TO "membership"`);
        await queryRunner.query(`CREATE TABLE "temporary_task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "description" varchar NOT NULL, "userId" integer, "teamId" integer, "priority" text NOT NULL DEFAULT ('media'), "estado" varchar CHECK( "estado" IN ('PENDIENTE','EN_CURSO','FINALIZADA','CANCELADA') ) NOT NULL DEFAULT ('PENDIENTE'), "dueDate" datetime, "fechaCreacion" datetime NOT NULL DEFAULT (datetime('now')), "historialEstadosId" integer, CONSTRAINT "FK_81dff849ce37d44c8821afdb197" FOREIGN KEY ("historialEstadosId") REFERENCES "historial_estado" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f316d3fe53497d4d8a2957db8b9" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de59b0c5e20f83310101e5ca835" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_task"("id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId") SELECT "id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId" FROM "task"`);
        await queryRunner.query(`DROP TABLE "task"`);
        await queryRunner.query(`ALTER TABLE "temporary_task" RENAME TO "task"`);
        await queryRunner.query(`CREATE TABLE "task_watcher" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "taskId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "UQ_dec52062bc494eb8addae2788f9" UNIQUE ("taskId", "userId"))`);
        await queryRunner.query(`CREATE TABLE "task_watcher_notification" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "eventType" varchar CHECK( "eventType" IN ('STATUS_CHANGE','PRIORITY_CHANGE','COMMENT_ADDED','TASK_UPDATED','DUE_DATE_CHANGE') ) NOT NULL, "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "readAt" datetime, "userId" integer NOT NULL, "taskId" integer NOT NULL, "triggeredById" integer)`);
        await queryRunner.query(`CREATE TABLE "temporary_membership" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rol" varchar CHECK( "rol" IN ('PROPIETARIO','MIEMBRO') ) NOT NULL DEFAULT ('MIEMBRO'), "fechaIngreso" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "teamId" integer NOT NULL, CONSTRAINT "UQ_8cbaee95bef7db57d99430b302b" UNIQUE ("userId", "teamId"), CONSTRAINT "FK_f587b1be7b7595b5af79a2fd008" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_membership"("id", "rol", "fechaIngreso", "userId", "teamId") SELECT "id", "rol", "fechaIngreso", "userId", "teamId" FROM "membership"`);
        await queryRunner.query(`DROP TABLE "membership"`);
        await queryRunner.query(`ALTER TABLE "temporary_membership" RENAME TO "membership"`);
        await queryRunner.query(`CREATE TABLE "temporary_task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "description" varchar NOT NULL, "userId" integer, "teamId" integer, "priority" text NOT NULL DEFAULT ('media'), "estado" varchar CHECK( "estado" IN ('PENDIENTE','EN_CURSO','FINALIZADA','CANCELADA') ) NOT NULL DEFAULT ('PENDIENTE'), "dueDate" datetime, "fechaCreacion" datetime NOT NULL DEFAULT (datetime('now')), "historialEstadosId" integer, CONSTRAINT "FK_81dff849ce37d44c8821afdb197" FOREIGN KEY ("historialEstadosId") REFERENCES "historial_estado" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f316d3fe53497d4d8a2957db8b9" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de59b0c5e20f83310101e5ca835" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_task"("id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId") SELECT "id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId" FROM "task"`);
        await queryRunner.query(`DROP TABLE "task"`);
        await queryRunner.query(`ALTER TABLE "temporary_task" RENAME TO "task"`);
        await queryRunner.query(`CREATE TABLE "temporary_task_watcher" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "taskId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "UQ_dec52062bc494eb8addae2788f9" UNIQUE ("taskId", "userId"), CONSTRAINT "FK_58a4f16b2d25d060de350ea5b73" FOREIGN KEY ("taskId") REFERENCES "task" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_9738bc7836805b483afda5e6f2f" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_task_watcher"("id", "createdAt", "updatedAt", "taskId", "userId") SELECT "id", "createdAt", "updatedAt", "taskId", "userId" FROM "task_watcher"`);
        await queryRunner.query(`DROP TABLE "task_watcher"`);
        await queryRunner.query(`ALTER TABLE "temporary_task_watcher" RENAME TO "task_watcher"`);
        await queryRunner.query(`CREATE TABLE "temporary_task_watcher_notification" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "eventType" varchar CHECK( "eventType" IN ('STATUS_CHANGE','PRIORITY_CHANGE','COMMENT_ADDED','TASK_UPDATED','DUE_DATE_CHANGE') ) NOT NULL, "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "readAt" datetime, "userId" integer NOT NULL, "taskId" integer NOT NULL, "triggeredById" integer, CONSTRAINT "FK_0a5a4f98b66bfc7642ee6660627" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_c169a29daf08be320f82dfd83a1" FOREIGN KEY ("taskId") REFERENCES "task" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_c223e65a2bb6094dfca82aa1bd8" FOREIGN KEY ("triggeredById") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_task_watcher_notification"("id", "eventType", "metadata", "createdAt", "readAt", "userId", "taskId", "triggeredById") SELECT "id", "eventType", "metadata", "createdAt", "readAt", "userId", "taskId", "triggeredById" FROM "task_watcher_notification"`);
        await queryRunner.query(`DROP TABLE "task_watcher_notification"`);
        await queryRunner.query(`ALTER TABLE "temporary_task_watcher_notification" RENAME TO "task_watcher_notification"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "task_watcher_notification" RENAME TO "temporary_task_watcher_notification"`);
        await queryRunner.query(`CREATE TABLE "task_watcher_notification" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "eventType" varchar CHECK( "eventType" IN ('STATUS_CHANGE','PRIORITY_CHANGE','COMMENT_ADDED','TASK_UPDATED','DUE_DATE_CHANGE') ) NOT NULL, "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "readAt" datetime, "userId" integer NOT NULL, "taskId" integer NOT NULL, "triggeredById" integer)`);
        await queryRunner.query(`INSERT INTO "task_watcher_notification"("id", "eventType", "metadata", "createdAt", "readAt", "userId", "taskId", "triggeredById") SELECT "id", "eventType", "metadata", "createdAt", "readAt", "userId", "taskId", "triggeredById" FROM "temporary_task_watcher_notification"`);
        await queryRunner.query(`DROP TABLE "temporary_task_watcher_notification"`);
        await queryRunner.query(`ALTER TABLE "task_watcher" RENAME TO "temporary_task_watcher"`);
        await queryRunner.query(`CREATE TABLE "task_watcher" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "taskId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "UQ_dec52062bc494eb8addae2788f9" UNIQUE ("taskId", "userId"))`);
        await queryRunner.query(`INSERT INTO "task_watcher"("id", "createdAt", "updatedAt", "taskId", "userId") SELECT "id", "createdAt", "updatedAt", "taskId", "userId" FROM "temporary_task_watcher"`);
        await queryRunner.query(`DROP TABLE "temporary_task_watcher"`);
        await queryRunner.query(`ALTER TABLE "task" RENAME TO "temporary_task"`);
        await queryRunner.query(`CREATE TABLE "task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "description" varchar NOT NULL, "userId" integer, "teamId" integer, "priority" text NOT NULL DEFAULT ('media'), "estado" varchar CHECK( "estado" IN ('PENDIENTE','EN_CURSO','FINALIZADA','CANCELADA') ) NOT NULL DEFAULT ('PENDIENTE'), "dueDate" datetime, "fechaCreacion" datetime NOT NULL DEFAULT (datetime('now')), "historialEstadosId" integer, CONSTRAINT "FK_81dff849ce37d44c8821afdb197" FOREIGN KEY ("historialEstadosId") REFERENCES "historial_estado" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f316d3fe53497d4d8a2957db8b9" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de59b0c5e20f83310101e5ca835" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "task"("id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId") SELECT "id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId" FROM "temporary_task"`);
        await queryRunner.query(`DROP TABLE "temporary_task"`);
        await queryRunner.query(`ALTER TABLE "membership" RENAME TO "temporary_membership"`);
        await queryRunner.query(`CREATE TABLE "membership" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rol" varchar CHECK( "rol" IN ('PROPIETARIO','MIEMBRO') ) NOT NULL DEFAULT ('MIEMBRO'), "fechaIngreso" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "teamId" integer NOT NULL, CONSTRAINT "UQ_8cbaee95bef7db57d99430b302b" UNIQUE ("userId", "teamId"), CONSTRAINT "FK_f587b1be7b7595b5af79a2fd008" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "membership"("id", "rol", "fechaIngreso", "userId", "teamId") SELECT "id", "rol", "fechaIngreso", "userId", "teamId" FROM "temporary_membership"`);
        await queryRunner.query(`DROP TABLE "temporary_membership"`);
        await queryRunner.query(`DROP TABLE "task_watcher_notification"`);
        await queryRunner.query(`DROP TABLE "task_watcher"`);
        await queryRunner.query(`ALTER TABLE "task" RENAME TO "temporary_task"`);
        await queryRunner.query(`CREATE TABLE "task" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "description" varchar NOT NULL, "userId" integer, "teamId" integer, "priority" text NOT NULL DEFAULT ('media'), "estado" varchar CHECK( "estado" IN ('PENDIENTE','EN_CURSO','FINALIZADA','CANCELADA') ) NOT NULL DEFAULT ('PENDIENTE'), "dueDate" datetime, "fechaCreacion" datetime NOT NULL DEFAULT (datetime('now')), "historialEstadosId" integer, CONSTRAINT "FK_81dff849ce37d44c8821afdb197" FOREIGN KEY ("historialEstadosId") REFERENCES "historial_estado" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f316d3fe53497d4d8a2957db8b9" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de59b0c5e20f83310101e5ca835" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "task"("id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId") SELECT "id", "title", "description", "userId", "teamId", "priority", "estado", "dueDate", "fechaCreacion", "historialEstadosId" FROM "temporary_task"`);
        await queryRunner.query(`DROP TABLE "temporary_task"`);
        await queryRunner.query(`ALTER TABLE "membership" RENAME TO "temporary_membership"`);
        await queryRunner.query(`CREATE TABLE "membership" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "rol" varchar CHECK( "rol" IN ('PROPIETARIO','MIEMBRO') ) NOT NULL DEFAULT ('MIEMBRO'), "fechaIngreso" datetime NOT NULL DEFAULT (datetime('now')), "userId" integer NOT NULL, "teamId" integer NOT NULL, CONSTRAINT "UQ_8cbaee95bef7db57d99430b302b" UNIQUE ("userId", "teamId"), CONSTRAINT "FK_f587b1be7b7595b5af79a2fd008" FOREIGN KEY ("teamId") REFERENCES "team" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "membership"("id", "rol", "fechaIngreso", "userId", "teamId") SELECT "id", "rol", "fechaIngreso", "userId", "teamId" FROM "temporary_membership"`);
        await queryRunner.query(`DROP TABLE "temporary_membership"`);
    }

}
