### Crear un admin

POST http://localhost:3000/users

Content-Type: application/json



{

  "name": "adminX",

  "rol": "admin"

}



### Crear un usuario

POST http://localhost:3000/users

Content-Type: application/json



{

  "name": "Ramiro",

  "rol": "user"

}

### Crear otro usuario

POST http://localhost:3000/users

Content-Type: application/json



{

  "name": "Sofia",

  "rol": "user"

}



### Crear un equipo

POST http://localhost:3000/teams

Content-Type: application/json



{

  "name":"Equipo C"

}





### Asignar usuario al equipo (userId: 2 al teamId: 1)

POST http://localhost:3000/teams/1/users/2



### Asignar admin al equipo (userId: 1 al teamId: 1)

POST http://localhost:3000/teams/1/users/1

### NUEVO: Actualizar nombre del equipo (solo admin del mismo equipo)
PUT http://localhost:3000/teams/1
Content-Type: application/json

{"name":"Equipo Actualizado 3","userId":2}

### Crear una tarea (solo admin del equipo)

POST http://localhost:3000/tasks

Content-Type: application/json



{

  "title": "Hacer entrega",

  "description": "Subir el trabajo final",

  "userId": 1,

  "teamId": 1

}

###crear otra tarea 
POST http://localhost:3000/tasks
Content-Type: application/json

{

  "title": "lavar los platos",

  "description": "lavalo bien no te hagas la loca",

  "userId": 2,

  "teamId": 1

}



### Marcar tarea como completa (userId: 2)

PUT http://localhost:3000/tasks/1/complete

Content-Type: application/json



{

  "userId": 2

}



### Listar tareas

GET http://localhost:3000/tasks



### Listar usuarios

GET http://localhost:3000/users



### Listar equipos

GET http://localhost:3000/teams